site_name: BOLD Best Practice
use_directory_urls: false
repo_url:
markdown_extensions:
  - toc:
      permalink: True
theme:
  name: "litera"
  features:
    - search.suggest 
plugins:
  - search
  - mknotebooks
nav:
  - Home:
    - 1 Ad hoc scripts: "1_adhocscripts.md"
    - 2 Clear layout structure: "2_clear_layout_structure.md"
    - 3 Coding standards: "3_coding_standards.md"
