site_name: BOLD Best Practice
use_directory_urls: false
repo_url:
docs_dir: "docs"
markdown_extensions:
theme:
  name: "material"
  highlightjs: true
  include_sidebar: true
  features:
    - search.suggest 
plugins:
  - search
  - mknotebooks
nav:
  - 1 Ad hoc scripts: "1_adhocscripts.md"
  - 2 Clear layout structure: "2_clear_layout_structure.md"
  - 3 Coding standards: "3_coding_standards.md"
