site_name: BOLD Best Practice
use_directory_urls: True
repo_url: https://github.com/mamonu/boldbestpractice
logo: "img/favicon.ico"
favicon: "img/favicon.ico"
markdown_extensions:
  - abbr
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
  - toc:
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: "material"
  features:
    - content.tabs.link
plugins:
  - search
  - mknotebooks
nav:
  - Home: "index.md"
  - 1 Ad hoc scripts: "1_adhocscripts.md"
  - 2 Reusable Code: "2_reusable_code.md"
  - 3 Clear layout structure: "3_clear_layout_structure.md"
  - 4 Coding standards: "4_coding_standards.md"
  - 5 Version Control: "5_version_control.md"
  - 6 Reproducible work: "6_repro_reusable_.md"
  - 7 QA and Testing: "7_QA_testing.md"
  - Contributing: "Contributing.md"
  - Appendix:
      - Org Infrastructure:
          - MOJ: "orgs/MOJ.md"
          - DHSC: "orgs/DHSC.md"
          - ONS: "orgs/ONS.md"
