site_name: BOLD Best Practice
use_directory_urls: false
repo_url:
markdown_extensions:
  - toc:
      permalink: True
theme:
  name: "bootstrap4"
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - search.highlight
    - search.share
    - search.suggest 
plugins:
  - search
  - mknotebooks
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      custom_templates: templates
nav:
  - BOLD Best Practice:
    - 1 Ad hoc scripts: "1_adhocscripts.md"
    - 2 Clear layout structure: "2_clear_layout_structure.md"
    - 3 Coding standards: "3_coding_standards.md"
