site_name: BOLD Best Practice
use_directory_urls: True
repo_url:
markdown_extensions:
theme:
  name: "material"
plugins:
  - search
  - mknotebooks
nav:
  - Home: "../README.md" 
  - 1 Ad hoc scripts: "1_adhocscripts.md"
  - 2 Clear layout structure: "2_clear_layout_structure.md"
  - 3 Coding standards: "3_coding_standards.md"
  - 4 Version Control: "4_version_control.md"
  - 5 Reproducible and Reusable work: "5_repro_reusable_.md"
  - 6 QA and Testing: "6_QA_testing.md"
  - Appendix:
    - Org Infrastructure:
      - MOJ:
      - DHSC:
      - ONS:
      
