site_name: BOLD Best Practice
use_directory_urls: True
repo_url: https://github.com/mamonu/boldbestpractice
logo: "img/favicon.ico"
favicon: "img/favicon.ico"
markdown_extensions:
  - abbr
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
  - toc:
      permalink: True
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: "material"
  features:
    - content.tabs.link
plugins:
  - search
  - mknotebooks
nav:
  - Home: "index.md" 
  - 1 Ad hoc scripts: "1_adhocscripts.md"
  - 2 Clear layout structure: "2_clear_layout_structure.md"
  - 3 Coding standards: "3_coding_standards.md"
  - 4 Version Control: "4_version_control.md"
  - 5 Reproducible and Reusable work: "5_repro_reusable_.md"
  - 6 QA and Testing: "6_QA_testing.md"
  - Contributing : "Contributing.md"
  - Appendix:
    - Org Infrastructure:
      - MOJ: "orgs/MOJ.md"
      - DHSC: "orgs/DHSC.md"
      - ONS: "orgs/ONS.md"
      
